In [1]:
import pandas as pd
import numpy as np

In [2]:
marks_df = pd.DataFrame([
    [100,80,10],
    [90,70,7],
    [120,100,14],
    [80,70,14],
    [80,70,14]
],columns=['iq','marks','package'])

marks_df

    iq  marks  package
0  100     80       10
1   90     70        7
2  120    100       14
3   80     70       14
4   80     70       14

In [3]:
# value_counts(): Returns the frequency of the value

marks_df.marks.value_counts()

marks
70     3
80     1
100    1
Name: count, dtype: int64

In [4]:
marks_df.value_counts()

iq   marks  package
80   70     14         2
90   70     7          1
100  80     10         1
120  100    14         1
Name: count, dtype: int64

In [5]:
# Find which player has won maximum no_of player_of_match award in final and qualifiers.


ipl[
    (ipl['MatchNumber'] == 'Final') |
    (ipl['MatchNumber'] == 'Qualifier 1')|
    (ipl['MatchNumber'] == 'Qualifier 2')
]  ['Player_of_Match'].value_counts()

NameError: name 'ipl' is not defined

In [ ]:
# sort_values()

s = pd.Series([1, 5, 7, 9, 5, 3, 4, 6, 2, 8])


s.sort_values(ascending = False)

3    9
9    8
2    7
7    6
1    5
4    5
6    4
5    3
8    2
0    1
dtype: int64

In [ ]:
ipl.sort_values(by = 'City')

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
135,1237180,Abu Dhabi,2020-11-08,2020/21,Qualifier 2,Delhi Capitals,Sunrisers Hyderabad,Sheikh Zayed Stadium,Delhi Capitals,bat,N,Delhi Capitals,Runs,17.0,NaN,MP Stoinis,"['MP Stoinis', 'S Dhawan', 'SS Iyer', 'SO Hetm...","['PK Garg', 'DA Warner', 'MK Pandey', 'KS Will...",PR Reiffel,S Ravi
95,1254098,Abu Dhabi,2021-09-26,2021,38,Kolkata Knight Riders,Chennai Super Kings,"Zayed Cricket Stadium, Abu Dhabi",Kolkata Knight Riders,bat,N,Chennai Super Kings,Wickets,2.0,NaN,RA Jadeja,"['Shubman Gill', 'VR Iyer', 'RA Tripathi', 'EJ...","['RD Gaikwad', 'F du Plessis', 'MM Ali', 'AT R...",CB Gaffaney,Tapan Sharma
533,729315,Abu Dhabi,2014-04-29,2014,19,Kolkata Knight Riders,Rajasthan Royals,Sheikh Zayed Stadium,Rajasthan Royals,bat,Y,Rajasthan Royals,SuperOver,NaN,NaN,JP Faulkner,"['G Gambhir', 'MS Bisla', 'JH Kallis', 'MK Pan...","['AM Rahane', 'KK Nair', 'SV Samson', 'SR Wats...",Aleem Dar,AK Chaudhary
181,1216503,Abu Dhabi,2020-10-01,2020/21,13,Mumbai Indians,Kings XI Punjab,Sheikh Zayed Stadium,Kings XI Punjab,field,N,Mumbai Indians,Runs,48.0,NaN,KA Pollard,"['Q de Kock', 'RG Sharma', 'SA Yadav', 'Ishan ...","['KL Rahul', 'MA Agarwal', 'KK Nair', 'N Poora...",VK Sharma,S Ravi
92,1254099,Abu Dhabi,2021-09-28,2021,42,Punjab Kings,Mumbai Indians,"Zayed Cricket Stadium, Abu Dhabi",Mumbai Indians,field,N,Mumbai Indians,Wickets,6.0,NaN,KA Pollard,"['KL Rahul', 'Mandeep Singh', 'CH Gayle', 'AK ...","['RG Sharma', 'Q de Kock', 'SA Yadav', 'SS Tiw...",S Ravi,VK Sharma
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
543,729295,NaN,2014-04-22,2014,9,Kings XI Punjab,Sunrisers Hyderabad,Sharjah Cricket Stadium,Sunrisers Hyderabad,field,N,Kings XI Punjab,Runs,72.0,NaN,GJ Maxwell,"['CA Pujara', 'V Sehwag', 'GJ Maxwell', 'DA Mi...","['AJ Finch', 'S Dhawan', 'DA Warner', 'KL Rahu...",M Erasmus,S Ravi
545,729291,NaN,2014-04-20,2014,7,Rajasthan Royals,Kings XI Punjab,Sharjah Cricket Stadium,Kings XI Punjab,field,N,Kings XI Punjab,Wickets,7.0,NaN,GJ Maxwell,"['AM Nayar', 'AM Rahane', 'SV Samson', 'SR Wat...","['CA Pujara', 'V Sehwag', 'WP Saha', 'GJ Maxwe...",BF Bowden,M Erasmus
546,729289,NaN,2014-04-19,2014,6,Kolkata Knight Riders,Delhi Daredevils,Dubai International Cricket Stadium,Kolkata Knight Riders,bat,N,Delhi Daredevils,Wickets,4.0,NaN,JP Duminy,"['JH Kallis', 'G Gambhir', 'MK Pandey', 'RV Ut...","['M Vijay', 'MA Agarwal', 'KD Karthik', 'LRPL ...",Aleem Dar,VA Kulkarni
547,729287,NaN,2014-04-19,2014,5,Royal Challengers Bangalore,Mumbai Indians,Dubai International Cricket Stadium,Royal Challengers Bangalore,field,N,Royal Challengers Bangalore,Wickets,7.0,NaN,PA Patel,"['NJ Maddinson', 'PA Patel', 'V Kohli', 'Yuvra...","['MEK Hussey', 'AP Tare', 'AT Rayudu', 'RG Sha...",Aleem Dar,AK Chaudhary
550,729281,NaN,2014-04-17,2014,2,Delhi Daredevils,Royal Challengers Bangalore,Sharjah Cricket Stadium,Royal Challengers Bangalore,field,N,Royal Challengers Bangalore,Wickets,8.0,NaN,YS Chahal,"['MA Agarwal', 'M Vijay', 'KD Karthik', 'MK Ti...","['PA Patel', 'NJ Maddinson', 'V Kohli', 'Yuvra...",Aleem Dar,S Ravi

In [ ]:
# rank():
# It ranks based on value.
# Remember, the one with the highest value, receives the lowest rank

batsman = pd.read_csv(r"D:\Nikss\Self Pracitce\Python from beginning (CampusX)\18 Session 18 - (DataFrame Methods)/00 batsman_runs_ipl.csv")
batsman

             batter  batsman_run
0    A Ashish Reddy          280
1          A Badoni          161
2        A Chandila            4
3          A Chopra           53
4       A Choudhary           25
..              ...          ...
600      Yash Dayal            0
601   Yashpal Singh           47
602     Younis Khan            3
603    Yuvraj Singh         2754
604          Z Khan          117

[605 rows x 2 columns]

In [ ]:
batsman['batsman_run'].rank(ascending = False)

0      166.5
1      226.0
2      535.0
3      329.0
4      402.5
       ...
600    594.0
601    343.0
602    547.5
603     27.0
604    256.0
Name: batsman_run, Length: 605, dtype: float64

In [ ]:
# rename(): Renames the columns

students = pd.DataFrame(
    {
        'name':['nitish','ankit','rupesh','harshit','mrityunjay','jenish','rishabh','parth','aditya','khilan'],
        'college':['bit','iit','vit','gmers','psmc','vlsi','ssit','ld','gsms','git'],
        'branch':['eee','it','cse','mbbs','me','ce','civ','cse','bio','mba'],
        'cgpa':[6.66,8.25,6.41,8,5.6,9.0,7.4,10,7.4,7.8],
        'package':[4,5,6,10,6,7,8,9,11,9.5]

    }
)

students

         name college branch   cgpa  package
0      nitish     bit    eee   6.66      4.0
1       ankit     iit     it   8.25      5.0
2      rupesh     vit    cse   6.41      6.0
3     harshit   gmers   mbbs   8.00     10.0
4  mrityunjay    psmc     me   5.60      6.0
5      jenish    vlsi     ce   9.00      7.0
6     rishabh    ssit    civ   7.40      8.0
7       parth      ld    cse  10.00      9.0
8      aditya    gsms    bio   7.40     11.0
9      khilan     git    mba   7.80      9.5

In [ ]:
cols = {'name': 'student', 'college': 'institute'}

students.rename(columns=cols)

      student institute branch   cgpa  package
0      nitish       bit    eee   6.66      4.0
1       ankit       iit     it   8.25      5.0
2      rupesh       vit    cse   6.41      6.0
3     harshit     gmers   mbbs   8.00     10.0
4  mrityunjay      psmc     me   5.60      6.0
5      jenish      vlsi     ce   9.00      7.0
6     rishabh      ssit    civ   7.40      8.0
7       parth        ld    cse  10.00      9.0
8      aditya      gsms    bio   7.40     11.0
9      khilan       git    mba   7.80      9.5

In [ ]:
# unique(): Will return the unique values

data = pd.Series([1, 2, 3, 4, 5, 1, 2, 5, 55, 45, 65, 75, np.nan, np.nan, np.nan])

data.unique()

array([ 1.,  2.,  3.,  4.,  5., 55., 45., 65., 75., nan])

In [ ]:
ipl['Season'].unique()

array(['2022', '2021', '2020/21', '2019', '2018', '2017', '2016', '2015',
       '2014', '2013', '2012', '2011', '2009/10', '2009', '2007/08'],
      dtype=object)

In [ ]:
# nunique(): Returns the no_of unique values. It doesn't count null values

data

0      1.0
1      2.0
2      3.0
3      4.0
4      5.0
5      1.0
6      2.0
7      5.0
8     55.0
9     45.0
10    65.0
11    75.0
12     NaN
13     NaN
14     NaN
dtype: float64

In [ ]:
data.nunique()

9

In [ ]:
ipl['Season'].nunique()

15

In [ ]:
# isnull(): This returns True if the value in null else False

ipl

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [ ]:
ipl.isnull()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
946,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
947,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
948,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
949,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False

In [ ]:
ipl['method']

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ...
945    NaN
946    NaN
947    NaN
948    NaN
949    NaN
Name: method, Length: 950, dtype: object

In [ ]:
# dropna(): This drops the null values

len(ipl)

950

In [ ]:
ipl.dropna(inplace= True)

In [ ]:
len(ipl)

19

In [ ]:
# fillna(): Fills the null values

s = pd.Series([1, 2, 3, 4, 5, np.nan, 6, 7, np.nan, 8, 9])
s

0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     NaN
6     6.0
7     7.0
8     NaN
9     8.0
10    9.0
dtype: float64

In [ ]:
s.fillna(100)

0       1.0
1       2.0
2       3.0
3       4.0
4       5.0
5     100.0
6       6.0
7       7.0
8     100.0
9       8.0
10      9.0
dtype: float64

In [ ]:
# dropduplicates(): Deletes the duplicate rows

data = {
    'Name': ['Nikunj', 'Jugal', 'Harshit', 'Jenish', 'Jugal', 'Harshit', 'Parth', 'Jenish', 'Parth'],
    'Surname': ['Bosamiya', 'Bosamiya', 'Kamani', 'Mer', 'Bosamiya', 'Kamani', 'Paghdar', 'Mer', 'Paghdar'],
    'City': ['Jetpur', 'Rajkot', 'Himmatnagar', 'Anand', 'Rajkot', 'Himmatnagar', 'Jetpur', 'Ahmedabad', 'Vadodara']
}

friends = pd.DataFrame(data)

friends

      Name   Surname         City
0   Nikunj  Bosamiya       Jetpur
1    Jugal  Bosamiya       Rajkot
2  Harshit    Kamani  Himmatnagar
3   Jenish       Mer        Anand
4    Jugal  Bosamiya       Rajkot
5  Harshit    Kamani  Himmatnagar
6    Parth   Paghdar       Jetpur
7   Jenish       Mer    Ahmedabad
8    Parth   Paghdar     Vadodara

In [ ]:
friends.drop_duplicates()

      Name   Surname         City
0   Nikunj  Bosamiya       Jetpur
1    Jugal  Bosamiya       Rajkot
2  Harshit    Kamani  Himmatnagar
3   Jenish       Mer        Anand
6    Parth   Paghdar       Jetpur
7   Jenish       Mer    Ahmedabad
8    Parth   Paghdar     Vadodara